### ISSUE TITLE
Getting error  while using ilp-plugin-xrp-escrow

### ISSUE THREAD

**Issue by manali103** [ripple/ilp-plugin-xrp-escrow#11]
Error: Cannot find module 'ilp-plugin-xrp-escrow'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/homel/DemoILP/Ripple/ilp-plugin-xrp-escrow-master/ilp-plugin-xrp-escrow.js:1:87)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)

**Comment by michielbdejong** [comment]
Since you seem to be running your script from inside the ilp-plugin-xrp-escrow-master folder, you should use `require('.')` where you would usually use `require('ilp-plugin-xrp-escrow')`. Alternatively, run `npm install ilp-plugin-xrp-escrow` from your terminal, which will download the module from npmjs.com and install it under `./node_modules`.

**Comment by manali103** [comment]
npm install ilp-plugin-xrp-escrow

output:npm ERR! code E404
npm ERR! 404 Not Found: ilp-plugin-xrp-escrow@latest

**Comment by michielbdejong** [comment]
Ah right, sorry. That's because of #6. Just use `require('.')` then in your test script.
